# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
input_data_file = "output_data/cities.csv"
cities_weather_df = pd.read_csv(input_data_file)

cities_weather_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,5924351,Clyde River,90,CA,1593362274,77,70.47,-68.59,32.00,9.17
1,5848280,Kapaa,90,US,1593361470,94,22.08,-159.32,73.40,7.96
2,1218420,Seydi,8,TM,1593362195,17,39.48,62.91,77.38,11.72
3,3995647,Moctezuma,1,MX,1593362195,37,29.80,-109.67,86.05,8.14
4,3874787,Punta Arenas,0,CL,1593362048,84,-53.15,-70.92,32.00,9.17
...,...,...,...,...,...,...,...,...,...,...
568,3671437,Caucayá,28,CO,1593362205,50,-0.19,-74.78,89.64,2.53
569,2214846,Misratah,0,LY,1593362346,51,32.38,15.09,80.17,16.91
570,697593,Pervomays'k,47,UA,1593362274,62,48.04,30.85,79.20,6.51
571,3386931,Tamandaré,57,BR,1593362274,82,-8.76,-35.10,77.85,11.59
572,3393115,Paracuru,0,BR,1593362274,72,-3.41,-39.03,81.00,20.00

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key = g_key)

locations = cities_weather_df[["Lat", "Lng"]].astype(float)
city_humidity = cities_weather_df["Humidity"].astype(float)

fig = gmaps.figure(center=(20.0, 0.0), zoom_level=3,
                  layout={'width': '1000px',
                    'height': '500px',
                    'padding': '3px',
                    'border': '1px solid black'})

city_heat_map = gmaps.heatmap_layer(locations, weights=city_humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(city_heat_map)
fig

Figure(layout=FigureLayout(border='1px solid black', height='500px', padding='3px', width='1000px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
new_cities_weather_df = cities_weather_df.loc[((cities_weather_df["Max Temp"] > 70) & (cities_weather_df["Max Temp"] < 80)) &
                                              (cities_weather_df["Wind Speed"] < 10) &
                                              (cities_weather_df["Cloudiness"] == 0) , :]

new_cities_weather_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
41,2312888,Mbanza-Ngungu,0,CD,1593362200,47,-5.25,14.87,77.99,4.07
218,699706,Novooleksiyivka,0,UA,1593362223,47,46.23,34.64,78.21,6.69
225,1140025,Herat Province,0,AF,1593362180,13,34.50,62.00,78.80,3.36
251,1513491,Yangi Marg`ilon,0,UZ,1593362307,27,40.43,71.72,73.40,2.24
254,3359638,Walvis Bay,0,NaN,1593362229,37,-22.96,14.51,71.60,6.93
258,4021858,Guerrero Negro,0,MX,1593362307,57,27.98,-114.06,74.30,5.93
356,296852,Erzin,0,TR,1593362244,87,36.96,36.20,78.01,4.00
366,1513087,Nurota,0,UZ,1593361733,15,40.56,65.69,75.20,9.17
392,1786657,Yinchuan,0,CN,1593362249,36,38.47,106.27,72.00,4.00
395,1805733,Jinchang,0,CN,1593362250,22,38.50,102.17,74.07,5.44

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
import json
hotel_df = new_cities_weather_df
hotel_df["Hotel Name"] = " "

#hotel_df
google_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "types": "hotel",
    "key": g_key,
}

for index, rows in hotel_df.iterrows():
    
    lat = rows["Lat"]
    lng = rows["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    data_response = requests.get(google_url,params)
    #print(data_response)
    
    try:
    
        data_json = data_response.json()
        hotel_df.loc[index, "Hotel Name"] = data_json["results"][0]["name"]
        #print(json.dumps(data_json, indent=4, sort_keys=False))
        #print(data_json["results"][0]["name"])
        
        
    except (KeyError, IndexError):
        print("**** Something is wrong with the data, please check. ****")
        

        
        
hotel_df

C:\Users\gleix\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\gleix\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
41,2312888,Mbanza-Ngungu,0,CD,1593362200,47,-5.25,14.87,77.99,4.07,Mbanza-Ngungu
218,699706,Novooleksiyivka,0,UA,1593362223,47,46.23,34.64,78.21,6.69,Novooleksiivka
225,1140025,Herat Province,0,AF,1593362180,13,34.50,62.00,78.80,3.36,Aybak
251,1513491,Yangi Marg`ilon,0,UZ,1593362307,27,40.43,71.72,73.40,2.24,Fergana
254,3359638,Walvis Bay,0,NaN,1593362229,37,-22.96,14.51,71.60,6.93,Walvis Bay
258,4021858,Guerrero Negro,0,MX,1593362307,57,27.98,-114.06,74.30,5.93,Guerrero Negro
356,296852,Erzin,0,TR,1593362244,87,36.96,36.20,78.01,4.00,Erzin
366,1513087,Nurota,0,UZ,1593361733,15,40.56,65.69,75.20,9.17,Nurota
392,1786657,Yinchuan,0,CN,1593362249,36,38.47,106.27,72.00,4.00,Yinchuan
395,1805733,Jinchang,0,CN,1593362250,22,38.50,102.17,74.07,5.44,Jinchang

In [6]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [7]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

fig.add_layer(markers)

fig

# Display figure

Figure(layout=FigureLayout(border='1px solid black', height='500px', padding='3px', width='1000px'))

In [8]:
hotel_info

['\n<dl>\n<dt>Name</dt><dd>Mbanza-Ngungu</dd>\n<dt>City</dt><dd>Mbanza-Ngungu</dd>\n<dt>Country</dt><dd>CD</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Novooleksiivka</dd>\n<dt>City</dt><dd>Novooleksiyivka</dd>\n<dt>Country</dt><dd>UA</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Aybak</dd>\n<dt>City</dt><dd>Herat Province</dd>\n<dt>Country</dt><dd>AF</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Fergana</dd>\n<dt>City</dt><dd>Yangi Marg`ilon</dd>\n<dt>Country</dt><dd>UZ</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Walvis Bay</dd>\n<dt>City</dt><dd>Walvis Bay</dd>\n<dt>Country</dt><dd>nan</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Guerrero Negro</dd>\n<dt>City</dt><dd>Guerrero Negro</dd>\n<dt>Country</dt><dd>MX</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Erzin</dd>\n<dt>City</dt><dd>Erzin</dd>\n<dt>Country</dt><dd>TR</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Nurota</dd>\n<dt>City</dt><dd>Nurota</dd>\n<dt>Country</dt><dd>UZ</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Yinchuan</dd>\n<dt>City</dt><dd>Yinchuan</dd>\n<dt>Country</dt><dd>CN</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Jinchang</dd>\n<dt>City</dt><dd>Jinchang</dd>\n<dt>Country</dt><dd>CN</dd>\n</dl>\n']