# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
input_data_file = "output_data/cities.csv"
cities_weather_df = pd.read_csv(input_data_file)

cities_weather_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,5924351,Clyde River,90,CA,1593362274,77,70.47,-68.59,32.00,9.17
1,5848280,Kapaa,90,US,1593361470,94,22.08,-159.32,73.40,7.96
2,1218420,Seydi,8,TM,1593362195,17,39.48,62.91,77.38,11.72
3,3995647,Moctezuma,1,MX,1593362195,37,29.80,-109.67,86.05,8.14
4,3874787,Punta Arenas,0,CL,1593362048,84,-53.15,-70.92,32.00,9.17
...,...,...,...,...,...,...,...,...,...,...
568,3671437,Caucayá,28,CO,1593362205,50,-0.19,-74.78,89.64,2.53
569,2214846,Misratah,0,LY,1593362346,51,32.38,15.09,80.17,16.91
570,697593,Pervomays'k,47,UA,1593362274,62,48.04,30.85,79.20,6.51
571,3386931,Tamandaré,57,BR,1593362274,82,-8.76,-35.10,77.85,11.59
572,3393115,Paracuru,0,BR,1593362274,72,-3.41,-39.03,81.00,20.00

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure